{
    "latitude": 39.7392358,
    "longitude": -104.990251,
    "timezone": "America/Denver",
    "currently": {
        "time": 1572802375,
        "summary": "Partly Cloudy",
        "icon": "partly-cloudy-day",
        "nearestStormDistance": 6,
        "nearestStormBearing": 25,
        "precipIntensity": 0,
        "precipProbability": 0,
        "temperature": 54.67,
        "apparentTemperature": 54.76,
        "dewPoint": 22.02,
        "humidity": 0.28,
        "pressure": 1013.7,
        "windSpeed": 4.96,
        "windGust": 14.26,
        "windBearing": 196,
        "cloudCover": 0.38,
        "uvIndex": 3,
        "visibility": 10,
        "ozone": 249
    },
    "minutely": {
        "summary": "Partly cloudy for the hour.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1572802320,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802380,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802920,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572802980,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803040,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803100,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803160,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803220,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803280,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803340,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803400,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803460,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803520,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803580,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803640,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803700,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803760,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803820,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803880,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572803940,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804000,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804060,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804120,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804180,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804240,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804300,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804360,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804420,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804600,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804660,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804720,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804780,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804840,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804900,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572804960,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805020,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805080,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805140,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805200,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805260,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805320,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805380,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1572805920,
                "precipIntensity": 0,
                "precipProbability": 0
            }
        ]
    },
    "hourly": {
        "summary": "Partly cloudy throughout the day.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1572800400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 51.68,
                "apparentTemperature": 51.68,
                "dewPoint": 22.03,
                "humidity": 0.31,
                "pressure": 1014.3,
                "windSpeed": 3.82,
                "windGust": 10.1,
                "windBearing": 134,
                "cloudCover": 0.38,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 248.7
            },
            {
                "time": 1572804000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.27,
                "apparentTemperature": 56.27,
                "dewPoint": 22,
                "humidity": 0.26,
                "pressure": 1013.5,
                "windSpeed": 5.98,
                "windGust": 17.15,
                "windBearing": 204,
                "cloudCover": 0.37,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 249.5
            },
            {
                "time": 1572807600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.34,
                "apparentTemperature": 55.34,
                "dewPoint": 23.25,
                "humidity": 0.29,
                "pressure": 1014,
                "windSpeed": 7.02,
                "windGust": 17.05,
                "windBearing": 99,
                "cloudCover": 0.48,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 250.9
            },
            {
                "time": 1572811200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.08,
                "apparentTemperature": 55.08,
                "dewPoint": 24.5,
                "humidity": 0.3,
                "pressure": 1013.5,
                "windSpeed": 6.37,
                "windGust": 15.21,
                "windBearing": 26,
                "cloudCover": 0.56,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 252.7
            },
            {
                "time": 1572814800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.44,
                "apparentTemperature": 56.44,
                "dewPoint": 24.04,
                "humidity": 0.28,
                "pressure": 1012.5,
                "windSpeed": 6.77,
                "windGust": 16.22,
                "windBearing": 341,
                "cloudCover": 0.53,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 254.1
            },
            {
                "time": 1572818400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0006,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 55.55,
                "apparentTemperature": 55.55,
                "dewPoint": 23.04,
                "humidity": 0.28,
                "pressure": 1012.1,
                "windSpeed": 7.15,
                "windGust": 17.31,
                "windBearing": 351,
                "cloudCover": 0.54,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 255.3
            },
            {
                "time": 1572822000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0008,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 52.36,
                "apparentTemperature": 52.36,
                "dewPoint": 21.98,
                "humidity": 0.3,
                "pressure": 1013,
                "windSpeed": 6.07,
                "windGust": 17.07,
                "windBearing": 327,
                "cloudCover": 0.67,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 256.5
            },
            {
                "time": 1572825600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0025,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 47.61,
                "apparentTemperature": 46.55,
                "dewPoint": 21.4,
                "humidity": 0.35,
                "pressure": 1013.9,
                "windSpeed": 3.46,
                "windGust": 11.63,
                "windBearing": 279,
                "cloudCover": 0.76,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 257.5
            },
            {
                "time": 1572829200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0009,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 44.93,
                "apparentTemperature": 43.49,
                "dewPoint": 20.92,
                "humidity": 0.38,
                "pressure": 1014.9,
                "windSpeed": 3.45,
                "windGust": 7.1,
                "windBearing": 244,
                "cloudCover": 0.8,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 258.7
            },
            {
                "time": 1572832800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0005,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 42.9,
                "apparentTemperature": 40.39,
                "dewPoint": 20.7,
                "humidity": 0.41,
                "pressure": 1015.6,
                "windSpeed": 4.33,
                "windGust": 8.69,
                "windBearing": 240,
                "cloudCover": 0.86,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 260.1
            },
            {
                "time": 1572836400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 41.45,
                "apparentTemperature": 38.94,
                "dewPoint": 20.82,
                "humidity": 0.43,
                "pressure": 1016.4,
                "windSpeed": 4.06,
                "windGust": 6.21,
                "windBearing": 211,
                "cloudCover": 0.88,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 261.2
            },
            {
                "time": 1572840000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0012,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 39.55,
                "apparentTemperature": 37.14,
                "dewPoint": 21.01,
                "humidity": 0.47,
                "pressure": 1016.9,
                "windSpeed": 3.65,
                "windGust": 5.43,
                "windBearing": 224,
                "cloudCover": 0.9,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 262.3
            },
            {
                "time": 1572843600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 38.81,
                "apparentTemperature": 36,
                "dewPoint": 21.01,
                "humidity": 0.48,
                "pressure": 1017.7,
                "windSpeed": 3.93,
                "windGust": 4.93,
                "windBearing": 191,
                "cloudCover": 0.91,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 263.3
            },
            {
                "time": 1572847200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0013,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 37.57,
                "apparentTemperature": 35.01,
                "dewPoint": 21.06,
                "humidity": 0.51,
                "pressure": 1018.4,
                "windSpeed": 3.51,
                "windGust": 3.94,
                "windBearing": 162,
                "cloudCover": 0.93,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 263.4
            },
            {
                "time": 1572850800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 34.49,
                "apparentTemperature": 31.5,
                "dewPoint": 22.23,
                "humidity": 0.61,
                "pressure": 1020.5,
                "windSpeed": 3.51,
                "windGust": 4.27,
                "windBearing": 203,
                "cloudCover": 0.85,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 261.7
            },
            {
                "time": 1572854400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0004,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 32.68,
                "apparentTemperature": 29.12,
                "dewPoint": 21.32,
                "humidity": 0.63,
                "pressure": 1020.8,
                "windSpeed": 3.77,
                "windGust": 4.72,
                "windBearing": 209,
                "cloudCover": 0.78,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 259.3
            },
            {
                "time": 1572858000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0005,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0026,
                "temperature": 31.11,
                "apparentTemperature": 27.23,
                "dewPoint": 20.74,
                "humidity": 0.65,
                "pressure": 1021.1,
                "windSpeed": 3.84,
                "windGust": 5.01,
                "windBearing": 258,
                "cloudCover": 0.74,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 258.5
            },
            {
                "time": 1572861600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0004,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0027,
                "temperature": 29.46,
                "apparentTemperature": 25.61,
                "dewPoint": 20.61,
                "humidity": 0.69,
                "pressure": 1021.5,
                "windSpeed": 3.62,
                "windGust": 4.9,
                "windBearing": 240,
                "cloudCover": 0.78,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 261.2
            },
            {
                "time": 1572865200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0004,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0026,
                "temperature": 28.12,
                "apparentTemperature": 24.64,
                "dewPoint": 20.54,
                "humidity": 0.73,
                "pressure": 1022,
                "windSpeed": 3.2,
                "windGust": 4.65,
                "windBearing": 206,
                "cloudCover": 0.87,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 265.7
            },
            {
                "time": 1572868800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0004,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.003,
                "temperature": 27.06,
                "apparentTemperature": 27.06,
                "dewPoint": 20.71,
                "humidity": 0.77,
                "pressure": 1022.3,
                "windSpeed": 2.86,
                "windGust": 4.25,
                "windBearing": 206,
                "cloudCover": 0.92,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 269.6
            },
            {
                "time": 1572872400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0004,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0038,
                "temperature": 26.88,
                "apparentTemperature": 26.88,
                "dewPoint": 21.21,
                "humidity": 0.79,
                "pressure": 1022.6,
                "windSpeed": 2.65,
                "windGust": 3.7,
                "windBearing": 206,
                "cloudCover": 0.89,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 272
            },
            {
                "time": 1572876000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0005,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0043,
                "temperature": 27.24,
                "apparentTemperature": 27.24,
                "dewPoint": 22.24,
                "humidity": 0.81,
                "pressure": 1022.9,
                "windSpeed": 2.53,
                "windGust": 3.06,
                "windBearing": 202,
                "cloudCover": 0.82,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 273.5
            },
            {
                "time": 1572879600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0006,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0042,
                "temperature": 29,
                "apparentTemperature": 29,
                "dewPoint": 23.26,
                "humidity": 0.79,
                "pressure": 1022.8,
                "windSpeed": 2.53,
                "windGust": 2.73,
                "windBearing": 181,
                "cloudCover": 0.75,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 275
            },
            {
                "time": 1572883200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0005,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0026,
                "temperature": 31.64,
                "apparentTemperature": 31.64,
                "dewPoint": 24.33,
                "humidity": 0.74,
                "pressure": 1022.1,
                "windSpeed": 2.72,
                "windGust": 3.01,
                "windBearing": 137,
                "cloudCover": 0.71,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 276.2
            },
            {
                "time": 1572886800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0003,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 34.99,
                "apparentTemperature": 32.65,
                "dewPoint": 25.66,
                "humidity": 0.68,
                "pressure": 1021.2,
                "windSpeed": 3.04,
                "windGust": 3.6,
                "windBearing": 82,
                "cloudCover": 0.67,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 277
            },
            {
                "time": 1572890400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 37.76,
                "apparentTemperature": 35.54,
                "dewPoint": 26.41,
                "humidity": 0.63,
                "pressure": 1020.2,
                "windSpeed": 3.24,
                "windGust": 3.88,
                "windBearing": 37,
                "cloudCover": 0.59,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 277.7
            },
            {
                "time": 1572894000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 40.31,
                "apparentTemperature": 38.51,
                "dewPoint": 27.02,
                "humidity": 0.59,
                "pressure": 1019.3,
                "windSpeed": 3.18,
                "windGust": 3.43,
                "windBearing": 36,
                "cloudCover": 0.45,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 278.3
            },
            {
                "time": 1572897600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 42.39,
                "apparentTemperature": 41.03,
                "dewPoint": 27.79,
                "humidity": 0.56,
                "pressure": 1018.7,
                "windSpeed": 3.03,
                "windGust": 3.03,
                "windBearing": 54,
                "cloudCover": 0.27,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 278.8
            },
            {
                "time": 1572901200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 43.49,
                "apparentTemperature": 43.49,
                "dewPoint": 28.28,
                "humidity": 0.55,
                "pressure": 1018.3,
                "windSpeed": 2.85,
                "windGust": 2.85,
                "windBearing": 64,
                "cloudCover": 0.13,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 279.1
            },
            {
                "time": 1572904800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 42.98,
                "apparentTemperature": 42.98,
                "dewPoint": 28.48,
                "humidity": 0.56,
                "pressure": 1018.7,
                "windSpeed": 2.65,
                "windGust": 2.65,
                "windBearing": 57,
                "cloudCover": 0.12,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 279.1
            },
            {
                "time": 1572908400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 41.13,
                "apparentTemperature": 41.13,
                "dewPoint": 28.87,
                "humidity": 0.61,
                "pressure": 1019.4,
                "windSpeed": 2.41,
                "windGust": 3.24,
                "windBearing": 38,
                "cloudCover": 0.12,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 278.9
            },
            {
                "time": 1572912000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 38.82,
                "apparentTemperature": 38.82,
                "dewPoint": 29.03,
                "humidity": 0.68,
                "pressure": 1020.4,
                "windSpeed": 2.32,
                "windGust": 3.7,
                "windBearing": 36,
                "cloudCover": 0.12,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 278.6
            },
            {
                "time": 1572915600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 36.94,
                "apparentTemperature": 36.94,
                "dewPoint": 28.12,
                "humidity": 0.7,
                "pressure": 1021.5,
                "windSpeed": 2.53,
                "windGust": 3.66,
                "windBearing": 80,
                "cloudCover": 0.12,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 278
            },
            {
                "time": 1572919200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 35.23,
                "apparentTemperature": 35.23,
                "dewPoint": 26.89,
                "humidity": 0.71,
                "pressure": 1022.6,
                "windSpeed": 2.92,
                "windGust": 3.43,
                "windBearing": 148,
                "cloudCover": 0.12,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 277.3
            },
            {
                "time": 1572922800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 34.2,
                "apparentTemperature": 31.49,
                "dewPoint": 25.85,
                "humidity": 0.71,
                "pressure": 1023.4,
                "windSpeed": 3.24,
                "windGust": 3.26,
                "windBearing": 196,
                "cloudCover": 0.13,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 276.4
            },
            {
                "time": 1572926400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 33.48,
                "apparentTemperature": 30.46,
                "dewPoint": 24.75,
                "humidity": 0.7,
                "pressure": 1024.1,
                "windSpeed": 3.42,
                "windGust": 3.43,
                "windBearing": 208,
                "cloudCover": 0.16,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 275.1
            },
            {
                "time": 1572930000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 32.98,
                "apparentTemperature": 29.74,
                "dewPoint": 23.43,
                "humidity": 0.68,
                "pressure": 1024.7,
                "windSpeed": 3.54,
                "windGust": 3.54,
                "windBearing": 202,
                "cloudCover": 0.19,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 273.8
            },
            {
                "time": 1572933600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 32.63,
                "apparentTemperature": 29.16,
                "dewPoint": 22.47,
                "humidity": 0.66,
                "pressure": 1025.1,
                "windSpeed": 3.68,
                "windGust": 3.69,
                "windBearing": 197,
                "cloudCover": 0.23,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 272.7
            },
            {
                "time": 1572937200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 32.09,
                "apparentTemperature": 28.37,
                "dewPoint": 22.04,
                "humidity": 0.66,
                "pressure": 1025.1,
                "windSpeed": 3.82,
                "windGust": 3.82,
                "windBearing": 205,
                "cloudCover": 0.26,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 272.2
            },
            {
                "time": 1572940800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0004,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 31.74,
                "apparentTemperature": 27.79,
                "dewPoint": 21.91,
                "humidity": 0.67,
                "pressure": 1024.9,
                "windSpeed": 3.99,
                "windGust": 3.99,
                "windBearing": 215,
                "cloudCover": 0.3,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 271.9
            },
            {
                "time": 1572944400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0005,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.002,
                "temperature": 30.99,
                "apparentTemperature": 26.77,
                "dewPoint": 21.79,
                "humidity": 0.68,
                "pressure": 1024.7,
                "windSpeed": 4.13,
                "windGust": 4.13,
                "windBearing": 216,
                "cloudCover": 0.32,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 271.9
            },
            {
                "time": 1572948000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0005,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0022,
                "temperature": 30.27,
                "apparentTemperature": 25.82,
                "dewPoint": 21.63,
                "humidity": 0.7,
                "pressure": 1024.7,
                "windSpeed": 4.23,
                "windGust": 4.23,
                "windBearing": 201,
                "cloudCover": 0.33,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 272.4
            },
            {
                "time": 1572951600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0004,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0019,
                "temperature": 29.61,
                "apparentTemperature": 24.95,
                "dewPoint": 21.5,
                "humidity": 0.71,
                "pressure": 1024.8,
                "windSpeed": 4.33,
                "windGust": 4.33,
                "windBearing": 197,
                "cloudCover": 0.33,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 273.2
            },
            {
                "time": 1572955200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0017,
                "temperature": 29.53,
                "apparentTemperature": 24.83,
                "dewPoint": 21.61,
                "humidity": 0.72,
                "pressure": 1024.9,
                "windSpeed": 4.35,
                "windGust": 4.35,
                "windBearing": 206,
                "cloudCover": 0.34,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 273.3
            },
            {
                "time": 1572958800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0012,
                "temperature": 29.87,
                "apparentTemperature": 25.2,
                "dewPoint": 21.64,
                "humidity": 0.71,
                "pressure": 1025,
                "windSpeed": 4.38,
                "windGust": 4.41,
                "windBearing": 196,
                "cloudCover": 0.41,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 272.3
            },
            {
                "time": 1572962400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 30.94,
                "apparentTemperature": 26.44,
                "dewPoint": 22.15,
                "humidity": 0.7,
                "pressure": 1025,
                "windSpeed": 4.38,
                "windGust": 4.8,
                "windBearing": 201,
                "cloudCover": 0.5,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 270.6
            },
            {
                "time": 1572966000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 33.41,
                "apparentTemperature": 29.45,
                "dewPoint": 23.26,
                "humidity": 0.66,
                "pressure": 1024.6,
                "windSpeed": 4.25,
                "windGust": 4.96,
                "windBearing": 213,
                "cloudCover": 0.55,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 269.4
            },
            {
                "time": 1572969600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 37.89,
                "apparentTemperature": 34.97,
                "dewPoint": 25.1,
                "humidity": 0.6,
                "pressure": 1023.7,
                "windSpeed": 3.91,
                "windGust": 4.34,
                "windBearing": 193,
                "cloudCover": 0.54,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 268.6
            },
            {
                "time": 1572973200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 43.65,
                "apparentTemperature": 42.05,
                "dewPoint": 26.98,
                "humidity": 0.52,
                "pressure": 1022.4,
                "windSpeed": 3.43,
                "windGust": 3.5,
                "windBearing": 157,
                "cloudCover": 0.48,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 268.2
            }
        ]
    },
    "daily": {
        "summary": "No precipitation throughout the week.",
        "icon": "clear-day",
        "data": [
            {
                "time": 1572760800,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1572787920,
                "sunsetTime": 1572825420,
                "moonPhase": 0.24,
                "precipIntensity": 0.0004,
                "precipIntensityMax": 0.0025,
                "precipIntensityMaxTime": 1572825660,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperatureHigh": 56.95,
                "temperatureHighTime": 1572815160,
                "temperatureLow": 26.38,
                "temperatureLowTime": 1572871440,
                "apparentTemperatureHigh": 56.45,
                "apparentTemperatureHighTime": 1572815160,
                "apparentTemperatureLow": 24.59,
                "apparentTemperatureLowTime": 1572864720,
                "dewPoint": 21.68,
                "humidity": 0.48,
                "pressure": 1015.6,
                "windSpeed": 3.9,
                "windGust": 17.71,
                "windGustTime": 1572805320,
                "windBearing": 128,
                "cloudCover": 0.45,
                "uvIndex": 4,
                "uvIndexTime": 1572805800,
                "visibility": 9.289,
                "ozone": 250.4,
                "temperatureMin": 28.76,
                "temperatureMinTime": 1572775140,
                "temperatureMax": 56.95,
                "temperatureMaxTime": 1572815160,
                "apparentTemperatureMin": 29.25,
                "apparentTemperatureMinTime": 1572775140,
                "apparentTemperatureMax": 56.45,
                "apparentTemperatureMaxTime": 1572815160
            },
            {
                "time": 1572850800,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1572874380,
                "sunsetTime": 1572911760,
                "moonPhase": 0.27,
                "precipIntensity": 0.0003,
                "precipIntensityMax": 0.0006,
                "precipIntensityMaxTime": 1572879420,
                "precipProbability": 0.11,
                "precipType": "rain",
                "temperatureHigh": 44.01,
                "temperatureHighTime": 1572901800,
                "temperatureLow": 29.01,
                "temperatureLowTime": 1572953940,
                "apparentTemperatureHigh": 43.6,
                "apparentTemperatureHighTime": 1572902100,
                "apparentTemperatureLow": 24.81,
                "apparentTemperatureLowTime": 1572954000,
                "dewPoint": 24.59,
                "humidity": 0.68,
                "pressure": 1021.6,
                "windSpeed": 3.06,
                "windGust": 5.02,
                "windGustTime": 1572858600,
                "windBearing": 173,
                "cloudCover": 0.47,
                "uvIndex": 3,
                "uvIndexTime": 1572893820,
                "visibility": 10,
                "ozone": 273.3,
                "temperatureMin": 26.38,
                "temperatureMinTime": 1572871440,
                "temperatureMax": 44.01,
                "temperatureMaxTime": 1572901800,
                "apparentTemperatureMin": 24.59,
                "apparentTemperatureMinTime": 1572864720,
                "apparentTemperatureMax": 43.6,
                "apparentTemperatureMaxTime": 1572902100
            },
            {
                "time": 1572937200,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1572960840,
                "sunsetTime": 1572998100,
                "moonPhase": 0.3,
                "precipIntensity": 0.0003,
                "precipIntensityMax": 0.0005,
                "precipIntensityMaxTime": 1573008840,
                "precipProbability": 0.08,
                "precipType": "rain",
                "temperatureHigh": 54.98,
                "temperatureHighTime": 1572987120,
                "temperatureLow": 30.17,
                "temperatureLowTime": 1573044960,
                "apparentTemperatureHigh": 54.48,
                "apparentTemperatureHighTime": 1572987120,
                "apparentTemperatureLow": 27.59,
                "apparentTemperatureLowTime": 1573044420,
                "dewPoint": 24.48,
                "humidity": 0.55,
                "pressure": 1023,
                "windSpeed": 3.53,
                "windGust": 4.98,
                "windGustTime": 1572965280,
                "windBearing": 193,
                "cloudCover": 0.36,
                "uvIndex": 3,
                "uvIndexTime": 1572979740,
                "visibility": 10,
                "ozone": 269.6,
                "temperatureMin": 29.01,
                "temperatureMinTime": 1572953940,
                "temperatureMax": 54.98,
                "temperatureMaxTime": 1572987120,
                "apparentTemperatureMin": 24.81,
                "apparentTemperatureMinTime": 1572954000,
                "apparentTemperatureMax": 54.48,
                "apparentTemperatureMaxTime": 1572987120
            },
            {
                "time": 1573023600,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1573047360,
                "sunsetTime": 1573084440,
                "moonPhase": 0.33,
                "precipIntensity": 0.0008,
                "precipIntensityMax": 0.0028,
                "precipIntensityMaxTime": 1573097040,
                "precipProbability": 0.14,
                "precipType": "rain",
                "temperatureHigh": 43.05,
                "temperatureHighTime": 1573073400,
                "temperatureLow": 25.67,
                "temperatureLowTime": 1573135200,
                "apparentTemperatureHigh": 38.99,
                "apparentTemperatureHighTime": 1573073520,
                "apparentTemperatureLow": 25.12,
                "apparentTemperatureLowTime": 1573121640,
                "dewPoint": 23.75,
                "humidity": 0.59,
                "pressure": 1025.8,
                "windSpeed": 4.58,
                "windGust": 10.37,
                "windGustTime": 1573095720,
                "windBearing": 13,
                "cloudCover": 0.39,
                "uvIndex": 4,
                "uvIndexTime": 1573066380,
                "visibility": 10,
                "ozone": 269.1,
                "temperatureMin": 30.17,
                "temperatureMinTime": 1573044960,
                "temperatureMax": 43.05,
                "temperatureMaxTime": 1573073400,
                "apparentTemperatureMin": 27.59,
                "apparentTemperatureMinTime": 1573044420,
                "apparentTemperatureMax": 38.99,
                "apparentTemperatureMaxTime": 1573073520
            },
            {
                "time": 1573110000,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1573133820,
                "sunsetTime": 1573170780,
                "moonPhase": 0.36,
                "precipIntensity": 0.0006,
                "precipIntensityMax": 0.0039,
                "precipIntensityMaxTime": 1573116480,
                "precipProbability": 0.13,
                "precipType": "rain",
                "temperatureHigh": 48.42,
                "temperatureHighTime": 1573161240,
                "temperatureLow": 32.58,
                "temperatureLowTime": 1573196520,
                "apparentTemperatureHigh": 47.92,
                "apparentTemperatureHighTime": 1573161240,
                "apparentTemperatureLow": 27.47,
                "apparentTemperatureLowTime": 1573218000,
                "dewPoint": 20.39,
                "humidity": 0.56,
                "pressure": 1030.7,
                "windSpeed": 3.37,
                "windGust": 8.08,
                "windGustTime": 1573115700,
                "windBearing": 56,
                "cloudCover": 0.06,
                "uvIndex": 3,
                "uvIndexTime": 1573152600,
                "visibility": 10,
                "ozone": 274.2,
                "temperatureMin": 25.67,
                "temperatureMinTime": 1573135200,
                "temperatureMax": 48.42,
                "temperatureMaxTime": 1573161240,
                "apparentTemperatureMin": 25.12,
                "apparentTemperatureMinTime": 1573121640,
                "apparentTemperatureMax": 47.92,
                "apparentTemperatureMaxTime": 1573161240
            },
            {
                "time": 1573196400,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1573220280,
                "sunsetTime": 1573257120,
                "moonPhase": 0.39,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipIntensityMaxTime": 1573225200,
                "precipProbability": 0,
                "temperatureHigh": 67.39,
                "temperatureHighTime": 1573246200,
                "temperatureLow": 38.43,
                "temperatureLowTime": 1573304340,
                "apparentTemperatureHigh": 66.89,
                "apparentTemperatureHighTime": 1573246200,
                "apparentTemperatureLow": 34.29,
                "apparentTemperatureLowTime": 1573304700,
                "dewPoint": 16.91,
                "humidity": 0.32,
                "pressure": 1025.2,
                "windSpeed": 4.87,
                "windGust": 6.68,
                "windGustTime": 1573273620,
                "windBearing": 212,
                "cloudCover": 0.24,
                "uvIndex": 4,
                "uvIndexTime": 1573238700,
                "visibility": 10,
                "ozone": 260,
                "temperatureMin": 32.58,
                "temperatureMinTime": 1573196520,
                "temperatureMax": 67.39,
                "temperatureMaxTime": 1573246200,
                "apparentTemperatureMin": 27.47,
                "apparentTemperatureMinTime": 1573218000,
                "apparentTemperatureMax": 66.89,
                "apparentTemperatureMaxTime": 1573246200
            },
            {
                "time": 1573282800,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1573306740,
                "sunsetTime": 1573343460,
                "moonPhase": 0.42,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipIntensityMaxTime": 1573365420,
                "precipProbability": 0,
                "temperatureHigh": 68.7,
                "temperatureHighTime": 1573330980,
                "temperatureLow": 40.36,
                "temperatureLowTime": 1573393200,
                "apparentTemperatureHigh": 68.2,
                "apparentTemperatureHighTime": 1573330980,
                "apparentTemperatureLow": 37.39,
                "apparentTemperatureLowTime": 1573393980,
                "dewPoint": 16.47,
                "humidity": 0.26,
                "pressure": 1019.8,
                "windSpeed": 6,
                "windGust": 25,
                "windGustTime": 1573342740,
                "windBearing": 222,
                "cloudCover": 0.84,
                "uvIndex": 3,
                "uvIndexTime": 1573326060,
                "visibility": 10,
                "ozone": 260,
                "temperatureMin": 38.43,
                "temperatureMinTime": 1573304340,
                "temperatureMax": 68.7,
                "temperatureMaxTime": 1573330980,
                "apparentTemperatureMin": 34.29,
                "apparentTemperatureMinTime": 1573304700,
                "apparentTemperatureMax": 68.2,
                "apparentTemperatureMaxTime": 1573330980
            },
            {
                "time": 1573369200,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1573393200,
                "sunsetTime": 1573429800,
                "moonPhase": 0.46,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0004,
                "precipIntensityMaxTime": 1573404900,
                "precipProbability": 0.04,
                "precipType": "rain",
                "temperatureHigh": 64.97,
                "temperatureHighTime": 1573419540,
                "temperatureLow": 41.97,
                "temperatureLowTime": 1573478760,
                "apparentTemperatureHigh": 64.47,
                "apparentTemperatureHighTime": 1573419540,
                "apparentTemperatureLow": 40.38,
                "apparentTemperatureLowTime": 1573479060,
                "dewPoint": 22.82,
                "humidity": 0.34,
                "pressure": 1019.9,
                "windSpeed": 4.75,
                "windGust": 9.24,
                "windGustTime": 1573449780,
                "windBearing": 109,
                "cloudCover": 0.46,
                "uvIndex": 3,
                "uvIndexTime": 1573412280,
                "visibility": 10,
                "ozone": 257.5,
                "temperatureMin": 40.36,
                "temperatureMinTime": 1573393200,
                "temperatureMax": 64.97,
                "temperatureMaxTime": 1573419540,
                "apparentTemperatureMin": 37.39,
                "apparentTemperatureMinTime": 1573393980,
                "apparentTemperatureMax": 64.47,
                "apparentTemperatureMaxTime": 1573419540
            }
        ]
    },
    "flags": {
        "sources": [
            "nwspa",
            "cmc",
            "gfs",
            "hrrr",
            "icon",
            "isd",
            "madis",
            "nam",
            "sref",
            "darksky",
            "nearest-precip"
        ],
        "nearest-station": 1.334,
        "units": "us"
    },
    "offset": -7
}
